try do
  print('hello')
end
except Exception as e do
end
finally do
end
